### ISSUE TITLE
Doesn't run on mac

### ISSUE THREAD

**Issue by nocte1337** [floneum/floneum#22]
When I run it, it just shows this 
![image](https://github.com/floneum/floneum/assets/38387234/2c9f4c02-8719-436d-be0f-8b2b02345b6f)
Macbook Pro M1 Pro running Ventura 13.4.1 (22F82)

**Comment by Demonthos** [comment]
👋 It looks like the application opened in a text editor?

I just uploaded a new release for mac that should fix this issue:

<img width="1166" alt="Screenshot 2023-07-20 at 7 09 57 PM" src="https://github.com/floneum/floneum/assets/66571940/370ce33b-348c-4180-a348-11442a3ce168">

Let me know if you have any more problems!

I'm still working on getting better release builds for Floneum. I would like to create an installer for all platforms in the future but that isn't set up yet.

**Comment by nocte1337** [comment]
Ok, I think I found a solution,
Basically the new executable you posted didn't work either, it just showed this:
![image](https://github.com/floneum/floneum/assets/38387234/bd135686-6699-46b5-9c41-138c1faea6c7)

So I decided to try to build it myself, after failing to do so because I had an old version of rust (1.66) 
I upgraded to the latest one, 
built it, 
the build executable (debug version, idk I'm not a rust dev) didn't work either, 
I came here to complain about that so I opened the executable you posted to make a screenshot and magically it started working,

I guess I needed to have the correct rust version installed to use it? I doesn't make much sense to me but ok.

FIXED

**Comment by Demonthos** [comment]
Hmm, rust doesn't have a runtime that is used when running the program as far as I know (unlike python, C#, and Java). It should be entirely contained in the binary.


It does take some time to open the application because Floneum needs to download the package manager. Once it has loaded, you should see some logs, but I could probably do a better job of logging any errors you encounter while loading or just logging progress while loading

<img width="931" alt="Screenshot 2023-07-22 at 3 52 55 PM" src="https://github.com/floneum/floneum/assets/66571940/4c827759-3141-49ab-8c88-a86836c51a54">

**Comment by nocte1337** [comment]
Yes I also couldn't understand, given that its not a script but a compiled executable.

When I was trying it first time I was on a different network which has a firewall (Stormshield), its a bit rare but maybe the firewall was blocking some connections and floneum was just exiting without logging anyting (I kept the terminal window open for at least 10 minutes while I was submitting the issue)
